services:
  # Servicio 1: Nuestra aplicación web Node.js
  web-app:
    build: .
    restart: on-failure
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .env

  # Servicio 2: Base de datos PostgreSQL
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  # Servicio 3: Visualización de Base de Datos (Adminer)
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  postgres_data:
